// Shared atoms — single source of truth for Unlighthouse vocabulary.
// Used across command schemas, hook payloads, and storage repositories.
// See v1.md §"Shared atoms" (lines 730–795).

import { z } from 'zod'

// Branded scan id — opaque to callers, generated by core.run().
const ScanIdSchema = z.string().min(1).brand<'ScanId'>()
export type ScanId = z.infer<typeof ScanIdSchema>

// Any reachable URL.
const UrlSchema = z.url()
export type Url = z.infer<typeof UrlSchema>

// Lighthouse-supported form factors. (D: 'mobile' is default; see D-020.)
const DeviceSchema = z.enum(['mobile', 'desktop'])
export type Device = z.infer<typeof DeviceSchema>

// Lighthouse audit categories (lhci.md-aligned).
const CategorySchema = z.enum(['performance', 'accessibility', 'seo', 'best-practices'])
export type Category = z.infer<typeof CategorySchema>

// Core Web Vitals + perf metrics (lab and field).
// LCP/INP/FCP/TTFB/TBT/SI in milliseconds. CLS is dimensionless float.
const MetricNameSchema = z.enum(['lcp', 'cls', 'inp', 'fcp', 'ttfb', 'tbt', 'si'])
export type MetricName = z.infer<typeof MetricNameSchema>

// Lifecycle states surfaced by the CrawlSession.
const ScanStatusSchema = z.enum([
  'starting',
  'discovering',
  'scanning',
  'paused',
  'complete',
  'cancelled',
  'error',
])
export type ScanStatus = z.infer<typeof ScanStatusSchema>

// Wire-format for UnlighthouseError. CLI / MCP serialise this on failure.
// See `contracts/errors` for the runtime class.
const StructuredErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  suggestion: z.string().optional(),
  docsUrl: z.url().optional(),
  cause: z.unknown().optional(),
})
export type StructuredError = z.infer<typeof StructuredErrorSchema>

// Page-based pagination (sqlite/postgres/D1 friendly).
function PaginatedSchema<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    total: z.number().int().nonnegative(),
    page: z.number().int().min(1),
    pageSize: z.number().int().min(1),
  })
}
export interface Paginated<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
}

// Aggregate scan summary, written when a scan completes.
const ScanSummarySchema = z.object({
  routes: z.number().int().nonnegative(),
  completed: z.number().int().nonnegative(),
  failed: z.number().int().nonnegative(),
  // Aggregate score 0..1 — `null` until at least one route has scored.
  scoreAverage: z.number().min(0).max(1).nullable(),
  scoresByCategory: z.partialRecord(CategorySchema, z.number().min(0).max(1)),
  durationMs: z.number().nonnegative(),
})
export type ScanSummary = z.infer<typeof ScanSummarySchema>

// A persisted scan row.
const ScanSchema = z.object({
  scanId: ScanIdSchema,
  site: UrlSchema,
  device: DeviceSchema,
  status: ScanStatusSchema,
  startedAt: z.iso.datetime(),
  completedAt: z.iso.datetime().nullable(),
  ciBranch: z.string().nullable(),
  ciCommit: z.string().nullable(),
  ciCommitMessage: z.string().nullable(),
  summary: ScanSummarySchema.nullable(),
})
export type Scan = z.infer<typeof ScanSchema>

// Per-route extracted metrics. Hot path; one row per audited URL.
// `routeName` is an optional human-readable route identifier sourced from seed
// metadata (e.g. sitemap entries); null when not available.
const ExtractedMetricsSchema = z.object({
  url: UrlSchema,
  path: z.string(),
  routeName: z.string().nullable(),
  scorePerformance: z.number().min(0).max(1).nullable(),
  scoreAccessibility: z.number().min(0).max(1).nullable(),
  scoreSeo: z.number().min(0).max(1).nullable(),
  scoreBestPractices: z.number().min(0).max(1).nullable(),
  lcp: z.number().nullable(),
  cls: z.number().nullable(),
  inp: z.number().nullable(),
  fcp: z.number().nullable(),
  ttfb: z.number().nullable(),
  tbt: z.number().nullable(),
  si: z.number().nullable(),
  lighthouseVersion: z.string(),
  capturedAt: z.iso.datetime(),
})
export type ExtractedMetrics = z.infer<typeof ExtractedMetricsSchema>

// Persisted route row — `ExtractedMetrics` joined with scan + blob keys.
const ScanRouteSchema = ExtractedMetricsSchema.extend({
  scanId: ScanIdSchema,
  lhrBlobKey: z.string(),
  // UI-reconciled report blob key. Nullable for rows persisted before the
  // reconciliation pipeline landed.
  reportBlobKey: z.string().nullish(),
})
export type ScanRoute = z.infer<typeof ScanRouteSchema>

// A seed URL produced by a SeedSource adapter.
const SeedSchema = z.object({
  url: UrlSchema,
  // Where the seed came from (sitemap, manual, fuse).
  source: z.string(),
  // Optional matcher hint (e.g. resolved RouteDefinition name).
  routeName: z.string().nullable().optional(),
})
export type Seed = z.infer<typeof SeedSchema>

// An assertion definition. Mirrors `core/comparison/assertions.ts`.
const AssertionSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('minScore'),
    category: CategorySchema,
    value: z.number().min(0).max(1),
  }),
  z.object({
    type: z.literal('maxNumericValue'),
    metric: MetricNameSchema,
    value: z.number().nonnegative(),
  }),
  z.object({
    type: z.literal('maxRegression'),
    metric: z.union([MetricNameSchema, CategorySchema]),
    value: z.number().nonnegative(),
  }),
])
export type Assertion = z.infer<typeof AssertionSchema>

// Result of an assertion evaluation against a single route or scan aggregate.
const AssertionResultSchema = z.object({
  assertion: AssertionSchema,
  passed: z.boolean(),
  actual: z.number().nullable(),
  url: UrlSchema.optional(),
  message: z.string().optional(),
})
export type AssertionResult = z.infer<typeof AssertionResultSchema>

export {
  AssertionSchema as Assertion,
  AssertionResultSchema as AssertionResult,
  CategorySchema as Category,
  DeviceSchema as Device,
  ExtractedMetricsSchema as ExtractedMetrics,
  MetricNameSchema as MetricName,
  PaginatedSchema as Paginated,
  ScanSchema as Scan,
  ScanIdSchema as ScanId,
  ScanRouteSchema as ScanRoute,
  ScanStatusSchema as ScanStatus,
  ScanSummarySchema as ScanSummary,
  SeedSchema as Seed,
  StructuredErrorSchema as StructuredError,
  UrlSchema as Url,
}
