// Shared atoms — single source of truth for Unlighthouse vocabulary.
// Used across command schemas, hook payloads, and storage repositories.
// See v1.md §"Shared atoms" (lines 730–795).

import { z } from 'zod'

// Branded scan id — opaque to callers, generated by core.run().
const ScanIdSchema = z.string().min(1).brand<'ScanId'>()
export type ScanId = z.infer<typeof ScanIdSchema>

// Any reachable URL.
const UrlSchema = z.url()
export type Url = z.infer<typeof UrlSchema>

// Lighthouse-supported form factors. (D: 'mobile' is default; see D-020.)
const DeviceSchema = z.enum(['mobile', 'desktop'])
export type Device = z.infer<typeof DeviceSchema>
export type NonEmptyArray<T> = [T, ...T[]]
export type DeviceMatrix = NonEmptyArray<Device>
const DeviceMatrixSchema = z.array(DeviceSchema).min(1) as unknown as z.ZodType<DeviceMatrix>

export function isDevice(value: unknown): value is Device {
  return value === 'mobile' || value === 'desktop'
}

export function normaliseDeviceMatrix(input: Device | readonly Device[] | null | undefined, fallback: Device = 'mobile'): DeviceMatrix {
  const raw = Array.isArray(input) ? input : input ? [input] : [fallback]
  const seen = new Set<Device>()
  const out: Device[] = []
  for (const device of raw) {
    if (!seen.has(device)) {
      seen.add(device)
      out.push(device)
    }
  }
  return (out.length ? out : [fallback]) as DeviceMatrix
}

export function parseScanId(value: string): ScanId {
  return ScanIdSchema.parse(value)
}

export function parseUrl(value: string): Url {
  return UrlSchema.parse(value)
}

// Lighthouse audit categories. Includes agentic-browsing added in LH 13.
const CategorySchema = z.enum(['performance', 'accessibility', 'seo', 'best-practices', 'agentic-browsing'])
export type Category = z.infer<typeof CategorySchema>

const CategoryScoreDisplayModeSchema = z.enum(['gauge', 'fraction'])
export type CategoryScoreDisplayMode = z.infer<typeof CategoryScoreDisplayModeSchema>

// Scan mode: 'site' crawls all pages, 'page' audits a single URL.
const ScanModeSchema = z.enum(['site', 'page'])
export type ScanMode = z.infer<typeof ScanModeSchema>

// Core Web Vitals + perf metrics (lab and field).
// LCP/INP/FCP/TTFB/TBT/SI in milliseconds. CLS is dimensionless float.
const MetricNameSchema = z.enum(['lcp', 'cls', 'inp', 'fcp', 'ttfb', 'tbt', 'si'])
export type MetricName = z.infer<typeof MetricNameSchema>

// Lifecycle states surfaced by the CrawlSession.
const ScanStatusSchema = z.enum([
  'starting',
  'discovering',
  'scanning',
  'paused',
  'complete',
  'cancelled',
  'error',
])
export type ScanStatus = z.infer<typeof ScanStatusSchema>

// Wire-format for UnlighthouseError. CLI / MCP serialise this on failure.
// See `contracts/errors` for the runtime class.
const StructuredErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  statusCode: z.number().int().min(100).max(599).optional(),
  category: z.enum(['fatal', 'route-failed', 'retryable', 'validation']).optional(),
  retryable: z.boolean().optional(),
  suggestion: z.string().optional(),
  docsUrl: z.url().optional(),
  details: z.record(z.string(), z.unknown()).optional(),
  cause: z.unknown().optional(),
})
export type StructuredError = z.infer<typeof StructuredErrorSchema>

// Page-based pagination (sqlite/postgres/D1 friendly).
function PaginatedSchema<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    total: z.number().int().nonnegative(),
    page: z.number().int().min(1),
    pageSize: z.number().int().min(1),
  })
}
export interface Paginated<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
}

// Aggregate scan summary, written when a scan completes.
const ScanSummarySchema = z.object({
  routes: z.number().int().nonnegative(),
  completed: z.number().int().nonnegative(),
  failed: z.number().int().nonnegative(),
  // Aggregate score 0..1 — `null` until at least one route has scored.
  scoreAverage: z.number().min(0).max(1).nullable(),
  scoresByCategory: z.partialRecord(CategorySchema, z.number().min(0).max(1)),
  // How each category score should be presented. Optional for summaries
  // written before LH13 display modes were persisted.
  categoryScoreDisplayModes: z.partialRecord(CategorySchema, CategoryScoreDisplayModeSchema).optional(),
  durationMs: z.number().nonnegative(),
  // Device matrix this scan covered. Lets the UI show "both" instead of just
  // the primary device for a mobile+desktop scan. Optional — older summaries
  // (and the scan row's primary `device`) predate it.
  devices: DeviceMatrixSchema.optional(),
})
export type ScanSummary = z.infer<typeof ScanSummarySchema>

// A persisted scan row.
const ScanSchema = z.object({
  scanId: ScanIdSchema,
  siteId: z.string().nullable(),
  site: UrlSchema,
  mode: ScanModeSchema,
  device: DeviceSchema,
  status: ScanStatusSchema,
  startedAt: z.iso.datetime(),
  completedAt: z.iso.datetime().nullable(),
  ciBranch: z.string().nullable(),
  ciCommit: z.string().nullable(),
  ciCommitMessage: z.string().nullable(),
  summary: ScanSummarySchema.nullable(),
})
export type Scan = z.infer<typeof ScanSchema>

// Per-route extracted metrics. Hot path; one row per audited URL.
const ExtractedMetricsSchema = z.object({
  url: UrlSchema,
  path: z.string(),
  routeName: z.string().nullable(),
  scorePerformance: z.number().min(0).max(1).nullable(),
  scoreAccessibility: z.number().min(0).max(1).nullable(),
  scoreSeo: z.number().min(0).max(1).nullable(),
  scoreBestPractices: z.number().min(0).max(1).nullable(),
  // Optional dimension: only the agentic-browsing category (LH13) populates
  // it, and rows from before it existed never will — so absent (undefined)
  // is as valid as null. nullish() tolerates both; the core score fields
  // stay strict nullable since every LHR carries them.
  scoreAgenticBrowsing: z.number().min(0).max(1).nullish(),
  lcp: z.number().nullable(),
  cls: z.number().nullable(),
  inp: z.number().nullable(),
  fcp: z.number().nullable(),
  ttfb: z.number().nullable(),
  tbt: z.number().nullable(),
  si: z.number().nullable(),
  lighthouseVersion: z.string(),
  // D-040: which auditor backend produced this row (`local` / `psi` /
  // `dataforseo` / …, or `split` when categories diverge). Additive + nullish —
  // pre-existing rows never had a choice, same treatment as scoreAgenticBrowsing.
  // Set by the adapter that actually ran, not the router.
  auditor: z.string().nullish(),
  capturedAt: z.iso.datetime(),
})
export type ExtractedMetrics = z.infer<typeof ExtractedMetricsSchema>

// Persisted route row — `ExtractedMetrics` joined with scan + blob keys.
//
// D-029: `device` is part of the row identity. The persisted PK is
// `(scanId, url, device)` so a scan can audit the same URL on mobile and
// desktop and store both results. Old single-device scans land here with
// `device: 'mobile'` (the historical default), which keeps the column
// non-null without requiring a backfill of rows that never had a choice.
const ScanRouteSchema = ExtractedMetricsSchema.extend({
  scanId: ScanIdSchema,
  device: DeviceSchema,
  lhrBlobKey: z.string(),
  reportBlobKey: z.string().nullish(),
  screenshotBlobKey: z.string().nullish(),
})
export type ScanRoute = z.infer<typeof ScanRouteSchema>

// D-030 — Reconciled report. Lean per-route projection of the raw LHR, written
// at scan ingest. Substrate that packs read from instead of re-parsing LHR
// JSON on every call; survives Lighthouse version drift because we only
// project the fields packs actually need.
//
// AuditFinding mirrors Lighthouse's per-audit shape but trims it to the
// fields that drive pack decisions. `severity` is derived at ingest time
// from (score, scoreDisplayMode) so packs don't have to reinvent the rule.
//
// `title` / `description` / `metricSavings` are pulled through so packs
// don't fall back to raw LHR just to read a human label or a savings number.
//
// `details.items` is projected per-audit ONLY for an allowlist of audit ids
// that packs actively need (image-* audits for the `images` pack, a11y
// element-level audits for `a11y-quick-wins`). Items are capped at 30 per
// audit and only the small set of fields below is kept. Packs that want
// the full LHR detail array still call getLhr — this projection keeps the
// blob bounded while making the common case (drill into one image / one
// element) hit a sub-MB cached blob instead of re-parsing 200KB of LHR.
const AuditDetailNodeSchema = z.object({
  selector: z.string().nullable(),
  snippet: z.string().nullable(),
  nodeLabel: z.string().nullable(),
})

const AuditDetailItemSchema = z.object({
  url: z.string().nullable(),
  type: z.string().nullable(),
  totalBytes: z.number().nullable(),
  wastedBytes: z.number().nullable(),
  node: AuditDetailNodeSchema.nullable(),
  snippet: z.string().nullable(),
  reason: z.string().nullable(),
  entity: z.string().nullable(),
  blockingTime: z.number().nullable(),
  transferSize: z.number().nullable(),
  wastedMs: z.number().nullable(),
})

const AuditFindingSchema = z.object({
  // Lighthouse audit id, e.g. 'uses-optimized-images' or 'image-delivery-insight'.
  id: z.string(),
  // 0..1 score. `null` for manual / notApplicable audits.
  score: z.number().nullable(),
  scoreDisplayMode: z.enum(['numeric', 'binary', 'informative', 'manual', 'notApplicable']),
  displayValue: z.string().nullable(),
  // Human-facing label from the LHR ("Document has a `<title>` element").
  title: z.string().nullable(),
  // Long-form remediation copy from the LHR. Nullable because some
  // informative audits ship without one.
  description: z.string().nullable(),
  // Pre-bucketed severity. `pass` = score ≥ 0.9, `warn` = ≥ 0.5, `fail` = < 0.5.
  // Manual / notApplicable / informative are always `pass` (they don't fail
  // a scan; packs filter them out by audit id).
  severity: z.enum(['pass', 'warn', 'fail']),
  // Lighthouse 12+ per-audit savings estimates. Populated on insight audits
  // (`*-insight` ids) and a few classic ones; absent fields = "no estimate
  // from Lighthouse," not "zero savings." Units: ms for LCP/FCP/INP/TBT,
  // dimensionless for CLS.
  metricSavings: z.object({
    LCP: z.number().optional(),
    FCP: z.number().optional(),
    INP: z.number().optional(),
    CLS: z.number().optional(),
    TBT: z.number().optional(),
  }).nullable(),
  // Capped + whitelisted per-item detail. Only populated for the small set
  // of audits the built-in packs depend on (see PROJECTED_DETAIL_AUDITS in
  // core/report/extract.ts). null for every other audit — packs fall through
  // to getLhr for those.
  items: z.array(AuditDetailItemSchema).nullable(),
})
export type AuditFinding = z.infer<typeof AuditFindingSchema>

const StackPackSchema = z.object({
  id: z.string(),
  title: z.string(),
  iconDataURL: z.string().nullable(),
  descriptions: z.record(z.string(), z.string()),
})
export type StackPack = z.infer<typeof StackPackSchema>

const EntitySchema = z.object({
  name: z.string(),
  isFirstParty: z.boolean(),
  origins: z.array(z.string()),
})
export type Entity = z.infer<typeof EntitySchema>

const ReconciledReportSchema = z.object({
  scanId: ScanIdSchema,
  url: UrlSchema,
  device: DeviceSchema,
  metrics: z.object({
    scorePerformance: z.number().min(0).max(1).nullable(),
    scoreAccessibility: z.number().min(0).max(1).nullable(),
    scoreSeo: z.number().min(0).max(1).nullable(),
    scoreBestPractices: z.number().min(0).max(1).nullable(),
    scoreAgenticBrowsing: z.number().min(0).max(1).nullish(),
    lcp: z.number().nullable(),
    cls: z.number().nullable(),
    inp: z.number().nullable(),
    fcp: z.number().nullable(),
    ttfb: z.number().nullable(),
    tbt: z.number().nullable(),
    si: z.number().nullable(),
  }),
  // String-keyed so unknown future categories (beyond the 5 in CategorySchema)
  // pass through without schema rejection.
  categories: z.record(z.string(), z.object({
    score: z.number().nullable(),
    categoryScoreDisplayMode: CategoryScoreDisplayModeSchema.nullish(),
    auditRefs: z.array(z.object({
      id: z.string(),
      weight: z.number().nonnegative(),
    })),
  })),
  audits: z.record(z.string(), AuditFindingSchema),
  provenance: z.object({
    lighthouseVersion: z.string(),
    userAgent: z.string().nullable(),
    capturedAt: z.iso.datetime(),
    benchmarkIndex: z.number().nullable(),
    timingTotal: z.number().nullable(),
    warnings: z.array(z.string()),
    runtimeError: z.object({ code: z.string(), message: z.string() }).nullable(),
    // D-040: the single backend that produced this report (or `split`).
    auditor: z.string().nullish(),
    // D-041: per-category backend when a split composer fanned categories to
    // different auditors ({ performance: 'local', seo: 'psi', … }).
    auditors: z.record(z.string(), z.string()).nullish(),
    // D-042: effective pool concurrency at capture time, so historical rows are
    // interpretable (a perf score from a contended run reads differently).
    concurrency: z.number().nullish(),
  }),
  stackPacks: z.array(StackPackSchema).nullable(),
  entities: z.array(EntitySchema).nullable(),
})
export type ReconciledReport = z.infer<typeof ReconciledReportSchema>

// A seed URL produced by a SeedSource adapter.
const SeedSchema = z.object({
  url: UrlSchema,
  // Where the seed came from (sitemap, manual, fuse).
  source: z.string(),
  // Optional matcher hint (e.g. resolved RouteDefinition name).
  routeName: z.string().nullable().optional(),
})
export type Seed = z.infer<typeof SeedSchema>

// An assertion definition. Mirrors `core/comparison/assertions.ts`.
const AssertionSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('minScore'),
    category: CategorySchema,
    value: z.number().min(0).max(1),
  }),
  z.object({
    type: z.literal('maxNumericValue'),
    metric: MetricNameSchema,
    value: z.number().nonnegative(),
  }),
  z.object({
    type: z.literal('maxRegression'),
    metric: z.union([MetricNameSchema, CategorySchema]),
    value: z.number().nonnegative(),
  }),
])
export type Assertion = z.infer<typeof AssertionSchema>

// Result of an assertion evaluation against a single route or scan aggregate.
const AssertionResultSchema = z.object({
  assertion: AssertionSchema,
  passed: z.boolean(),
  actual: z.number().nullable(),
  url: UrlSchema.optional(),
  message: z.string().optional(),
})
export type AssertionResult = z.infer<typeof AssertionResultSchema>

// Schemas are exported under their own names (`FooSchema`). Types live on
// the inferred `Foo`. Past iterations re-exported `FooSchema as Foo` which
// shadowed the type and broke tsc's declaration emitter — TS4025/TS4033
// because the same identifier was bound to both a value and a type. Keeping
// them separate matches the Zod community convention and makes published
// .d.ts files honest.
export {
  AssertionResultSchema,
  AssertionSchema,
  AuditFindingSchema,
  CategorySchema,
  CategoryScoreDisplayModeSchema,
  DeviceMatrixSchema,
  DeviceSchema,
  EntitySchema,
  ExtractedMetricsSchema,
  MetricNameSchema,
  PaginatedSchema,
  ReconciledReportSchema,
  ScanIdSchema,
  ScanModeSchema,
  ScanRouteSchema,
  ScanSchema,
  ScanStatusSchema,
  ScanSummarySchema,
  SeedSchema,
  StackPackSchema,
  StructuredErrorSchema,
  UrlSchema,
}
