// Shared atoms — single source of truth for Unlighthouse vocabulary.
// Used across command schemas, hook payloads, and storage repositories.
// See v1.md §"Shared atoms" (lines 730–795).

import { z } from 'zod'

// Branded scan id — opaque to callers, generated by core.run().
const ScanIdSchema = z.string().min(1).brand<'ScanId'>()
export type ScanId = z.infer<typeof ScanIdSchema>

// Any reachable URL.
const UrlSchema = z.url()
export type Url = z.infer<typeof UrlSchema>

// Lighthouse-supported form factors. (D: 'mobile' is default; see D-020.)
const DeviceSchema = z.enum(['mobile', 'desktop'])
export type Device = z.infer<typeof DeviceSchema>

// Lighthouse audit categories (lhci.md-aligned).
const CategorySchema = z.enum(['performance', 'accessibility', 'seo', 'best-practices'])
export type Category = z.infer<typeof CategorySchema>

// Core Web Vitals + perf metrics (lab and field).
// LCP/INP/FCP/TTFB/TBT/SI in milliseconds. CLS is dimensionless float.
const MetricNameSchema = z.enum(['lcp', 'cls', 'inp', 'fcp', 'ttfb', 'tbt', 'si'])
export type MetricName = z.infer<typeof MetricNameSchema>

// Lifecycle states surfaced by the CrawlSession.
const ScanStatusSchema = z.enum([
  'starting',
  'discovering',
  'scanning',
  'paused',
  'complete',
  'cancelled',
  'error',
])
export type ScanStatus = z.infer<typeof ScanStatusSchema>

// Wire-format for UnlighthouseError. CLI / MCP serialise this on failure.
// See `contracts/errors` for the runtime class.
const StructuredErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  suggestion: z.string().optional(),
  docsUrl: z.url().optional(),
  cause: z.unknown().optional(),
})
export type StructuredError = z.infer<typeof StructuredErrorSchema>

// Page-based pagination (sqlite/postgres/D1 friendly).
function PaginatedSchema<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    total: z.number().int().nonnegative(),
    page: z.number().int().min(1),
    pageSize: z.number().int().min(1),
  })
}
export interface Paginated<T> {
  items: T[]
  total: number
  page: number
  pageSize: number
}

// Aggregate scan summary, written when a scan completes.
const ScanSummarySchema = z.object({
  routes: z.number().int().nonnegative(),
  completed: z.number().int().nonnegative(),
  failed: z.number().int().nonnegative(),
  // Aggregate score 0..1 — `null` until at least one route has scored.
  scoreAverage: z.number().min(0).max(1).nullable(),
  scoresByCategory: z.partialRecord(CategorySchema, z.number().min(0).max(1)),
  durationMs: z.number().nonnegative(),
})
export type ScanSummary = z.infer<typeof ScanSummarySchema>

// A persisted scan row.
const ScanSchema = z.object({
  scanId: ScanIdSchema,
  site: UrlSchema,
  device: DeviceSchema,
  status: ScanStatusSchema,
  startedAt: z.iso.datetime(),
  completedAt: z.iso.datetime().nullable(),
  ciBranch: z.string().nullable(),
  ciCommit: z.string().nullable(),
  ciCommitMessage: z.string().nullable(),
  summary: ScanSummarySchema.nullable(),
})
export type Scan = z.infer<typeof ScanSchema>

// Per-route extracted metrics. Hot path; one row per audited URL.
// `routeName` is an optional human-readable route identifier sourced from seed
// metadata (e.g. sitemap entries); null when not available.
const ExtractedMetricsSchema = z.object({
  url: UrlSchema,
  path: z.string(),
  routeName: z.string().nullable(),
  scorePerformance: z.number().min(0).max(1).nullable(),
  scoreAccessibility: z.number().min(0).max(1).nullable(),
  scoreSeo: z.number().min(0).max(1).nullable(),
  scoreBestPractices: z.number().min(0).max(1).nullable(),
  lcp: z.number().nullable(),
  cls: z.number().nullable(),
  inp: z.number().nullable(),
  fcp: z.number().nullable(),
  ttfb: z.number().nullable(),
  tbt: z.number().nullable(),
  si: z.number().nullable(),
  lighthouseVersion: z.string(),
  capturedAt: z.iso.datetime(),
})
export type ExtractedMetrics = z.infer<typeof ExtractedMetricsSchema>

// Persisted route row — `ExtractedMetrics` joined with scan + blob keys.
//
// D-029: `device` is part of the row identity. The persisted PK is
// `(scanId, url, device)` so a scan can audit the same URL on mobile and
// desktop and store both results. Old single-device scans land here with
// `device: 'mobile'` (the historical default), which keeps the column
// non-null without requiring a backfill of rows that never had a choice.
const ScanRouteSchema = ExtractedMetricsSchema.extend({
  scanId: ScanIdSchema,
  device: DeviceSchema,
  lhrBlobKey: z.string(),
  // UI-reconciled report blob key. Nullable for rows persisted before the
  // reconciliation pipeline landed.
  reportBlobKey: z.string().nullish(),
})
export type ScanRoute = z.infer<typeof ScanRouteSchema>

// D-030 — Reconciled report. Lean per-route projection of the raw LHR, written
// at scan ingest. Substrate that packs read from instead of re-parsing LHR
// JSON on every call; survives Lighthouse version drift because we only
// project the fields packs actually need.
//
// AuditFinding mirrors Lighthouse's per-audit shape but trims it to the
// fields that drive pack decisions. `severity` is derived at ingest time
// from (score, scoreDisplayMode) so packs don't have to reinvent the rule.
//
// `title` / `description` / `metricSavings` are pulled through so packs
// don't fall back to raw LHR just to read a human label or a savings number.
//
// `details.items` is projected per-audit ONLY for an allowlist of audit ids
// that packs actively need (image-* audits for the `images` pack, a11y
// element-level audits for `a11y-quick-wins`). Items are capped at 30 per
// audit and only the small set of fields below is kept. Packs that want
// the full LHR detail array still call getLhr — this projection keeps the
// blob bounded while making the common case (drill into one image / one
// element) hit a sub-MB cached blob instead of re-parsing 200KB of LHR.
const AuditDetailNodeSchema = z.object({
  selector: z.string().nullable(),
  snippet: z.string().nullable(),
  nodeLabel: z.string().nullable(),
})

const AuditDetailItemSchema = z.object({
  // URL-shaped fields (image-* audits + render-blocking-insight).
  url: z.string().nullable(),
  // For audits that emit an item type (LHR distinguishes 'node' from
  // checklist rows on lcp-discovery-insight, for example).
  type: z.string().nullable(),
  totalBytes: z.number().nullable(),
  wastedBytes: z.number().nullable(),
  // Element-level data for a11y / element audits.
  node: AuditDetailNodeSchema.nullable(),
  snippet: z.string().nullable(),
  // First sub-item's reason field — image-delivery-insight stuffs the
  // remediation hint there. We keep only the first to bound size.
  reason: z.string().nullable(),
})

const AuditFindingSchema = z.object({
  // Lighthouse audit id, e.g. 'uses-optimized-images' or 'image-delivery-insight'.
  id: z.string(),
  // 0..1 score. `null` for manual / notApplicable audits.
  score: z.number().nullable(),
  scoreDisplayMode: z.enum(['numeric', 'binary', 'informative', 'manual', 'notApplicable']),
  displayValue: z.string().nullable(),
  // Human-facing label from the LHR ("Document has a `<title>` element").
  title: z.string().nullable(),
  // Long-form remediation copy from the LHR. Nullable because some
  // informative audits ship without one.
  description: z.string().nullable(),
  // Pre-bucketed severity. `pass` = score ≥ 0.9, `warn` = ≥ 0.5, `fail` = < 0.5.
  // Manual / notApplicable / informative are always `pass` (they don't fail
  // a scan; packs filter them out by audit id).
  severity: z.enum(['pass', 'warn', 'fail']),
  // Lighthouse 12+ per-audit savings estimates. Populated on insight audits
  // (`*-insight` ids) and a few classic ones; absent fields = "no estimate
  // from Lighthouse," not "zero savings." Units: ms for LCP/FCP/INP/TBT,
  // dimensionless for CLS.
  metricSavings: z.object({
    LCP: z.number().optional(),
    FCP: z.number().optional(),
    INP: z.number().optional(),
    CLS: z.number().optional(),
    TBT: z.number().optional(),
  }).nullable(),
  // Capped + whitelisted per-item detail. Only populated for the small set
  // of audits the built-in packs depend on (see PROJECTED_DETAIL_AUDITS in
  // core/report/extract.ts). null for every other audit — packs fall through
  // to getLhr for those.
  items: z.array(AuditDetailItemSchema).nullable(),
})
export type AuditFinding = z.infer<typeof AuditFindingSchema>

const ReconciledReportSchema = z.object({
  scanId: ScanIdSchema,
  url: UrlSchema,
  device: DeviceSchema,
  // Metric atoms minus the identity fields already on the parent row.
  metrics: z.object({
    scorePerformance: z.number().min(0).max(1).nullable(),
    scoreAccessibility: z.number().min(0).max(1).nullable(),
    scoreSeo: z.number().min(0).max(1).nullable(),
    scoreBestPractices: z.number().min(0).max(1).nullable(),
    lcp: z.number().nullable(),
    cls: z.number().nullable(),
    inp: z.number().nullable(),
    fcp: z.number().nullable(),
    ttfb: z.number().nullable(),
    tbt: z.number().nullable(),
    si: z.number().nullable(),
  }),
  // Per-category roll-ups: score + the audit refs that contributed (so packs
  // can iterate a category without walking the full audits map). `weight`
  // mirrors Lighthouse's category weighting — load-bearing for severity rules
  // like seo-basics' `severityFromWeight` (is-crawlable carries weight 3-4,
  // most others weight 1).
  categories: z.partialRecord(CategorySchema, z.object({
    score: z.number().nullable(),
    auditRefs: z.array(z.object({
      id: z.string(),
      weight: z.number().nonnegative(),
    })),
  })),
  // Per-audit findings keyed by Lighthouse audit id.
  audits: z.record(z.string(), AuditFindingSchema),
  provenance: z.object({
    lighthouseVersion: z.string(),
    userAgent: z.string().nullable(),
    capturedAt: z.iso.datetime(),
  }),
})
export type ReconciledReport = z.infer<typeof ReconciledReportSchema>

// A seed URL produced by a SeedSource adapter.
const SeedSchema = z.object({
  url: UrlSchema,
  // Where the seed came from (sitemap, manual, fuse).
  source: z.string(),
  // Optional matcher hint (e.g. resolved RouteDefinition name).
  routeName: z.string().nullable().optional(),
})
export type Seed = z.infer<typeof SeedSchema>

// An assertion definition. Mirrors `core/comparison/assertions.ts`.
const AssertionSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('minScore'),
    category: CategorySchema,
    value: z.number().min(0).max(1),
  }),
  z.object({
    type: z.literal('maxNumericValue'),
    metric: MetricNameSchema,
    value: z.number().nonnegative(),
  }),
  z.object({
    type: z.literal('maxRegression'),
    metric: z.union([MetricNameSchema, CategorySchema]),
    value: z.number().nonnegative(),
  }),
])
export type Assertion = z.infer<typeof AssertionSchema>

// Result of an assertion evaluation against a single route or scan aggregate.
const AssertionResultSchema = z.object({
  assertion: AssertionSchema,
  passed: z.boolean(),
  actual: z.number().nullable(),
  url: UrlSchema.optional(),
  message: z.string().optional(),
})
export type AssertionResult = z.infer<typeof AssertionResultSchema>

// Schemas are exported under their own names (`FooSchema`). Types live on
// the inferred `Foo`. Past iterations re-exported `FooSchema as Foo` which
// shadowed the type and broke tsc's declaration emitter — TS4025/TS4033
// because the same identifier was bound to both a value and a type. Keeping
// them separate matches the Zod community convention and makes published
// .d.ts files honest.
export {
  AssertionResultSchema,
  AssertionSchema,
  AuditFindingSchema,
  CategorySchema,
  DeviceSchema,
  ExtractedMetricsSchema,
  MetricNameSchema,
  PaginatedSchema,
  ReconciledReportSchema,
  ScanIdSchema,
  ScanRouteSchema,
  ScanSchema,
  ScanStatusSchema,
  ScanSummarySchema,
  SeedSchema,
  StructuredErrorSchema,
  UrlSchema,
}
