catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - crux-api
  - '!docs'
catalog:
  '@antfu/eslint-config': ^7.2.0
  '@arethetypeswrong/cli': 0.18.2
  '@types/fs-extra': ^11.0.4
  '@types/lodash': ^4.17.23
  '@types/lodash-es': ^4.17.12
  '@types/object-hash': ^3.0.6
  '@types/three': ^0.182.0
  '@types/ws': ^8.18.1
  '@vitejs/plugin-vue': ^6.0.3
  '@vue/compiler-sfc': ^3.5.27
  bumpp: ^10.4.0
  eslint: ^9.39.2
  obuild: ^0.4.20
  typescript: ^5.9.3
  vitest: ^4.0.18

catalogs:
  crux-api:
    nitropack: latest
  dependencies:
    '@clack/prompts': ^0.11.0
    '@headlessui/vue': ^1.7.23
    '@iconify-json/carbon': latest
    '@iconify-json/ic': latest
    '@iconify-json/icomoon-free': latest
    '@iconify-json/la': latest
    '@iconify-json/logos': latest
    '@iconify-json/mdi': latest
    '@iconify-json/simple-line-icons': latest
    '@iconify-json/vscode-icons': latest
    '@lhci/utils': ^0.15.1
    '@nuxt/ui': ^4.4.0
    '@puppeteer/browsers': ^2.11.1
    '@tailwindcss/vite': ^4.1.18
    '@unrouted/core': ^0.6.0
    '@unrouted/fetch': ^0.6.0
    '@unrouted/plugins': ^0.6.0
    '@unrouted/preset-api': ^0.6.0
    '@unrouted/preset-node': ^0.6.0
    '@vueuse/core': ^14.1.0
    '@vueuse/router': ^14.1.0
    axios: ^1.13.2
    better-opn: ^3.0.2
    c12: ^3.3.3
    cac: ^6.7.14
    cheerio: 1.1.0
    chrome-launcher: ^1.2.1
    consola: ^3.4.2
    date-fns: ^4.1.0
    dayjs: ^1.11.19
    defu: ^6.1.4
    execa: ^9.6.1
    fs-extra: ^11.3.3
    fuse.js: ^7.1.0
    globby: ^16.1.0
    h3: ^1.15.5
    hookable: ^6.0.1
    launch-editor: ^2.12.0
    lighthouse: ^13.0.1
    lightweight-charts: ^5.1.0
    listhen: ^1.9.0
    lodash-es: ^4.17.23
    minimist: ^1.2.8
    mlly: ^1.8.0
    object-hash: ^3.0.0
    ofetch: ^1.5.1
    pathe: ^2.0.3
    puppeteer-cluster: ^0.25.0
    puppeteer-core: ^24.36.0
    radix3: ^1.1.2
    regexparam: ^3.0.0
    sanitize-filename: ^1.6.3
    sitemapper: ^4.0.2
    slugify: ^1.6.6
    std-env: ^3.10.0
    tailwindcss: ^4.1.18
    three: ^0.182.0
    ufo: ^1.6.3
    unconfig: ^7.4.2
    unctx: ^2.5.0
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    vite: ^7.3.1
    vite-plugin-pages: ^0.33.2
    vue: ^3.5.27
    wrap-ansi: ^9.0.2
    ws: ^8.19.0
ignoredBuiltDependencies:
  - vue-demi
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
packageExtensions:
  puppeteer-cluster:
    peerDependencies:
      puppeteer-core: '*'
    peerDependenciesMeta:
      puppeteer:
        optional: true
