import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    './src/index.ts',
    './src/logger.ts',
    './src/core.ts',
    './src/report/index.ts',
    './src/comparison/index.ts',
    './src/seeds/index.ts',
    './src/policies/index.ts',
    './src/crawlers/index.ts',
    './src/auditors/index.ts',
    './src/auditors/mock.ts',
    './src/auditors/cdp-connect.ts',
    './src/auditors/remote-lighthouse.ts',
    './src/auditors/crux.ts',
    './src/auditors/dataforseo.ts',
    './src/auditors/local.ts',
    './src/auditors/psi.ts',
    './src/auditors/route/index.ts',
    './src/auditors/local-worker.ts',
    './src/storage/index.ts',
    './src/storage/drizzle/index.ts',
    './src/storage/drizzle/init-sql.ts',
    './src/storage/memory/index.ts',
    './src/storage/unstorage-blobs/index.ts',
    './src/api/index.ts',
    './src/api/client.ts',
    './src/api/static-client.ts',
    './src/api/http.ts',
    './src/api/handlers/index.ts',
    './src/api/dashboard.ts',
    './src/packs/index.ts',
    './src/util/fetch.ts',
    './src/util/filter.ts',
    './src/util/progressBox.ts',
    './src/util/misc.ts',
    './src/util/path.ts',
    './src/util/git-meta.ts',
    './src/persist-events.ts',
  ],
  format: 'esm',
  dts: true,
  platform: 'node',
})
