import type { RouteDiff } from '@unlighthouse/contracts/commands'
import type { Category } from '@unlighthouse/contracts/types/atoms'
import type { CategoryDelta, CompareThresholds } from './route-comparison'
import { isRouteCategory } from '../route-metrics'
import { CATEGORY_LABEL } from './route-comparison'

const TOP_N = 5

export interface RenderCompareMarkdownOptions {
  title: string
  baseScanId: string
  currentScanId: string
  thresholds: CompareThresholds
  regressions: RouteDiff[]
  improvements: RouteDiff[]
  added: RouteDiff[]
  removed: RouteDiff[]
  categoryDeltas: CategoryDelta[]
  overallBase: number | null
  overallCurrent: number | null
}

export function renderCompareMarkdown(opts: RenderCompareMarkdownOptions): string {
  const categoryThreshold = opts.thresholds.performance ?? 0.05
  const overallDelta = opts.overallBase != null && opts.overallCurrent != null
    ? opts.overallCurrent - opts.overallBase
    : 0
  const overallArrow = opts.overallBase != null && opts.overallCurrent != null
    ? deltaArrow(overallDelta, categoryThreshold)
    : '−'

  const verdictWord = opts.regressions.length
    ? 'Regressions detected'
    : opts.improvements.length
      ? 'Improvements detected'
      : 'No significant change'

  const lines: string[] = []
  lines.push(`## ${opts.title}`)
  lines.push('')
  lines.push(`**${verdictWord}** — overall score ${scoreCell(opts.overallBase)} → ${scoreCell(opts.overallCurrent)} ${overallArrow} (${signed(overallDelta)})`)
  lines.push('')
  lines.push(`Comparing base \`${opts.baseScanId.slice(0, 8)}\` → current \`${opts.currentScanId.slice(0, 8)}\` · ${opts.regressions.length} regression${opts.regressions.length === 1 ? '' : 's'}, ${opts.improvements.length} improvement${opts.improvements.length === 1 ? '' : 's'}.`)

  lines.push('')
  lines.push('### Category scores')
  lines.push('')
  lines.push('| Category | Base | Current | Δ |')
  lines.push('|----------|------|---------|---|')
  for (const delta of opts.categoryDeltas) {
    const valueDelta = delta.delta ?? 0
    const arrow = delta.base != null && delta.current != null
      ? deltaArrow(valueDelta, categoryThreshold)
      : '−'
    lines.push(`| ${delta.label} | ${scoreCell(delta.base)} | ${scoreCell(delta.current)} | ${arrow} ${signed(valueDelta)} |`)
  }

  const topRegressions = pickTopRouteDiffs(opts.regressions, 'regression')
  if (topRegressions.length) {
    lines.push('')
    lines.push(`### Worst regressions (top ${topRegressions.length})`)
    lines.push('')
    lines.push('| Route | Device | Category | Base | Current | Δ |')
    lines.push('|-------|--------|----------|------|---------|---|')
    for (const diff of topRegressions) {
      const arrow = deltaArrow(diff.delta, categoryThreshold)
      lines.push(`| \`${diff.url}\` | ${diff.device} | ${CATEGORY_LABEL[diff.metric as Category]} | ${scoreCell(diff.base)} | ${scoreCell(diff.current)} | ${arrow} ${signed(diff.delta)} |`)
    }
  }

  const topImprovements = pickTopRouteDiffs(opts.improvements, 'improvement')
  if (topImprovements.length) {
    lines.push('')
    lines.push(`### Best improvements (top ${topImprovements.length})`)
    lines.push('')
    lines.push('| Route | Device | Category | Base | Current | Δ |')
    lines.push('|-------|--------|----------|------|---------|---|')
    for (const diff of topImprovements) {
      const arrow = deltaArrow(diff.delta, categoryThreshold)
      lines.push(`| \`${diff.url}\` | ${diff.device} | ${CATEGORY_LABEL[diff.metric as Category]} | ${scoreCell(diff.base)} | ${scoreCell(diff.current)} | ${arrow} ${signed(diff.delta)} |`)
    }
  }

  if (opts.added.length) {
    lines.push('')
    lines.push(`### Added routes (${opts.added.length})`)
    lines.push('')
    for (const diff of opts.added.slice(0, TOP_N))
      lines.push(`- \`${diff.url}\` (${diff.device}) — Performance ${scoreCell(diff.current)}`)
    if (opts.added.length > TOP_N)
      lines.push(`- … and ${opts.added.length - TOP_N} more`)
  }

  if (opts.removed.length) {
    lines.push('')
    lines.push(`### Removed routes (${opts.removed.length})`)
    lines.push('')
    for (const diff of opts.removed.slice(0, TOP_N))
      lines.push(`- \`${diff.url}\` (${diff.device}) — was Performance ${scoreCell(diff.base)}`)
    if (opts.removed.length > TOP_N)
      lines.push(`- … and ${opts.removed.length - TOP_N} more`)
  }

  lines.push('')
  lines.push('<sub>Generated by [Unlighthouse](https://unlighthouse.dev).</sub>')

  return `${lines.join('\n')}\n`
}

function scoreCell(value: number | null | undefined): string {
  if (value == null)
    return '—'
  return String(Math.round(value * 100))
}

function deltaArrow(delta: number, threshold: number): string {
  if (delta > threshold)
    return '▲'
  if (-delta > threshold)
    return '▼'
  return '−'
}

function signed(delta: number): string {
  if (delta === 0)
    return '0'
  const value = Math.round(delta * 100)
  return value > 0 ? `+${value}` : `${value}`
}

function pickTopRouteDiffs(diffs: RouteDiff[], mode: 'regression' | 'improvement'): RouteDiff[] {
  const scoreDiffs = diffs.filter(diff => isRouteCategory(diff.metric))
  const byRoute = new Map<string, RouteDiff>()

  for (const diff of scoreDiffs) {
    const key = `${diff.url}|${diff.device}`
    const incumbent = byRoute.get(key)
    if (!incumbent) {
      byRoute.set(key, diff)
      continue
    }

    const incumbentBetter = mode === 'regression'
      ? incumbent.delta <= diff.delta
      : incumbent.delta >= diff.delta
    if (!incumbentBetter)
      byRoute.set(key, diff)
  }

  const sorted = [...byRoute.values()].sort((a, b) =>
    mode === 'regression' ? a.delta - b.delta : b.delta - a.delta,
  )
  return sorted.slice(0, TOP_N)
}
