// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BtnAction: typeof import('./src/components/Btn/BtnAction.vue')['default']
    BtnBasic: typeof import('./src/components/Btn/BtnBasic.vue')['default']
    BtnIcon: typeof import('./src/components/Btn/BtnIcon.vue')['default']
    Contributors: typeof import('./src/components/Contributors.vue')['default']
    DevelopmentWarning: typeof import('./src/components/DevelopmentWarning.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ICarbonBook: typeof import('~icons/carbon/book')['default']
    ICarbonFavoriteFilled: typeof import('~icons/carbon/favorite-filled')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    ICarbonPageLast: typeof import('~icons/carbon/page-last')['default']
    ICarbonTerminal: typeof import('~icons/carbon/terminal')['default']
    LighthouseThreeD: typeof import('./src/components/LighthouseThreeD.vue')['default']
  }
}

export { }
