// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BtnAction: typeof import('./src/components/Btn/BtnAction.vue')['default']
    BtnBasic: typeof import('./src/components/Btn/BtnBasic.vue')['default']
    BtnIcon: typeof import('./src/components/Btn/BtnIcon.vue')['default']
    Contributors: typeof import('./src/components/Contributors.vue')['default']
    DevelopmentWarning: typeof import('./src/components/DevelopmentWarning.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ICarbonCheckmarkOutline: typeof import('~icons/carbon/checkmark-outline')['default']
    ICarbonCloseOutline: typeof import('~icons/carbon/close-outline')['default']
    ICarbonFavoriteFilled: typeof import('~icons/carbon/favorite-filled')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    ICarbonWarningAlt: typeof import('~icons/carbon/warning-alt')['default']
    ILogosNuxtIcon: typeof import('~icons/logos/nuxt-icon')['default']
    ILogosVitejs: typeof import('~icons/logos/vitejs')['default']
    ILogosWebpack: typeof import('~icons/logos/webpack')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorBanner: typeof import('./src/components/SponsorBanner.vue')['default']
  }
}

export {}
