// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    'Carbon:compare': typeof import('virtual:vite-icons/carbon/compare')['default']
    'Carbon:list': typeof import('virtual:vite-icons/carbon/list')['default']
    'Carbon:listBoxes': typeof import('virtual:vite-icons/carbon/list-boxes')['default']
    'Carbon:logoGithub': typeof import('virtual:vite-icons/carbon/logo-github')['default']
    'Carbon:renew': typeof import('virtual:vite-icons/carbon/renew')['default']
    'Carbon:textWrap': typeof import('virtual:vite-icons/carbon/text-wrap')['default']
    CarbonArrowLeft: typeof import('virtual:vite-icons/carbon/arrow-left')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    Container: typeof import('./components/Container.vue')['default']
    DiffEditor: typeof import('./components/DiffEditor.vue')['default']
    ModuleId: typeof import('./components/ModuleId.vue')['default']
    ModuleList: typeof import('./components/ModuleList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
  }
}

export { }
