// Canonical names for runtime failures that are observable but non-fatal to the
// caller path. Keep names stable: hosts can persist/group these records.

export const OPERATIONAL_LOG_CATALOG = {
  'api.request_body_parse_failed': 'HTTP request body could not be parsed; route params continue into schema validation',
  'api.output_contract_mismatch': 'Handler response did not match its declared command output schema',
  'api.unhandled_error': 'API handler threw an unexpected error before it was converted to an error envelope',
  'api.error_body_read_failed': 'HTTP error response body could not be read for diagnostics',

  'core.hook_failed': 'A scan hook subscriber threw after the event was buffered',
  'core.scan_event_subscriber_failed': 'An in-memory scan event subscriber threw while receiving a live event',
  'core.session_cleanup_rejection': 'Session cleanup observed a rejected scan promise',
  'core.stale_scan_reap_failed': 'Boot-time stale scan cleanup failed for one scan row',
  'core.scan_error_persist_failed': 'Core failed to persist a terminal scan error state',
  'core.event_persist_flush_failed': 'Stable scan event log flush failed after the scan reached a terminal state',

  'scan.site_create_failed': 'Best-effort site row creation failed while starting a scan',
  'scan.site_association_failed': 'Scan could not be associated with a normalized site row',
  'host.output_cleanup_failed': 'Host failed to clear an output directory before scan boot',
  'host.client_resolve_failed': 'Host failed to resolve the bundled UI client package',
  'host.static_asset_probe_failed': 'Host static file probe failed for a reason other than file absence',
  'host.site_validation_failed': 'Host preflight request could not validate the configured site before scanning',
  'host.launch_path_rejected': 'Editor launch request was rejected because the resolved file path escaped the project root',
  'host.static_snapshot_build_failed': 'Static dashboard snapshot build failed and the offline report will degrade',
  'host.static_snapshot_pack_failed': 'Static dashboard pack pre-run failed and the offline pack cache will omit that pack',
  'host.static_screenshot_extract_failed': 'Static dashboard screenshot extraction from an LHR blob failed',
  'cli.chrome_reap_failed': 'CLI failed to reap leaked Lighthouse Chrome processes during shutdown',
  'cli.shutdown_server_close_failed': 'CLI shutdown failed while closing the HTTP listener',
  'cli.shutdown_scan_cancel_failed': 'CLI shutdown failed while cancelling the active scan',
  'cli.shutdown_db_close_failed': 'CLI shutdown failed while closing the storage handle',
  'cli.compare_baseline_missing': 'CLI compare mode could not find a previous scan baseline',
  'github_action.pr_context_parse_failed': 'GitHub Action could not parse the event payload for PR comment context',
  'github_action.response_body_read_failed': 'GitHub Action could not read an HTTP response body for diagnostics',
  'seeds.sitemap_wire_failed': 'Host failed to wire sitemap seed source during startup',
  'seeds.sitemap_fetch_failed': 'Sitemap seed source failed to fetch or parse sitemap routes',
  'seeds.sitemap_origin_mismatch': 'Sitemap routes were ignored because their origin differs from the configured site',
  'seeds.dynamic_sampling_applied': 'Dynamic route sampling reduced the routes that will be scanned',
  'seeds.route_definitions_scan_failed': 'Route-definitions seed source could not scan the configured pages directory',
  'seeds.route_definitions_wire_failed': 'Host failed to wire the route-definitions seed source during startup',
  'robots.missing': 'robots.txt could not be found or fetched for the configured site',
  'scan.reconciled_report_write_failed': 'Legacy per-route reconciled report blob write failed; required route artifacts continued',
  'scan.screenshot_extract_failed': 'Optional full-page screenshot extraction failed',
  'scan.screenshot_write_failed': 'Optional full-page screenshot blob write failed',
  'scan.finalize_probe_failed': 'Scan finalize could not read the existing scan row before proceeding',
  'scan.lifecycle_probe_failed': 'Scan lifecycle could not read the current scan row while handling a terminal error',
  'scan.lifecycle_error_persist_failed': 'Scan lifecycle failed to persist a terminal error state',
  'scan.pack_failed': 'A built-in report pack failed while scan completion continued',
  'scan.pack_system_failed': 'The report pack system failed while scan completion continued',

  'pack.report_schema_to_json_schema_failed': 'pack.list could not convert a pack\'s reportSchema to JSON Schema; that pack\'s reportSchema degraded to null',
  'pack.cached_report_invalid': 'A persisted pack report no longer matched its owning reportSchema and was rebuilt',

  'storage.old_blob_delete_failed': 'Old report blob deletion failed after the replacement report was persisted',
  'storage.migration_statement_failed': 'Storage init skipped a schema statement after it failed with a tolerated error',
  'storage.local_cache_delete_failed': 'Storage init failed to delete a stale local SQLite cache file during schema repair',
  'compare.pack_cache_read_failed': 'Compare pack-cache read failed and degraded to an empty pack list',
  'dashboard.pack_runs_read_failed': 'Dashboard route detail failed to read pack runs and degraded the pack panel',

  'auditor.cleanup_failed': 'Auditor/browser cleanup failed after an audit or worker task settled',

  'cloudflare.scan_event_fanout_failed': 'Live scan event fan-out to ScanEventsDO failed',
  'cloudflare.scan_target_rejected': 'A scan.start target URL was rejected by the host-supplied allowedTargets SSRF policy',
  'cloudflare.scan_events_invalid_payload': 'ScanEventsDO producer sent an invalid JSON event payload',
  'cloudflare.websocket_send_failed': 'ScanEventsDO websocket send failed; socket was closed',
  'cloudflare.websocket_close_failed': 'ScanEventsDO websocket close failed',
  'cloudflare.scan_control_persist_failed': 'ScanRunnerDO failed to persist a pause/resume/cancel state update',
  'cloudflare.scan_progress_persist_failed': 'ScanRunnerDO failed to persist live scan progress',
  'cloudflare.container_stop_failed': 'Best-effort Lighthouse container stop failed after scan termination',
  'cloudflare.link_discovery_failed': 'Sitemap-less Cloudflare link discovery failed for a scanned page',
  'cloudflare.link_discovery_url_skipped': 'Malformed Cloudflare-discovered link was skipped',
  'cloudflare.site_create_failed': 'Cloudflare scan runner site row creation failed while starting a scan',
  'cloudflare.site_association_failed': 'Cloudflare scan runner could not associate a scan with a normalized site row',
  'cloudflare.lighthouse_container_error': 'Cloudflare Lighthouse container Durable Object reported a runtime error',
  'lighthouse_container.config_missing': 'Lighthouse container started without required audit configuration',
  'lighthouse_container.uncaught_exception': 'Lighthouse container process emitted an uncaught exception',
  'lighthouse_container.unhandled_rejection': 'Lighthouse container process emitted an unhandled rejection',
  'lighthouse_container.audit_failed': 'Lighthouse container failed an audit request',
  'lighthouse_container.server_error': 'Lighthouse container HTTP server emitted an error',

  'ui.scan_hydrate_failed': 'Dashboard failed to hydrate the active scan from API snapshots',
  'ui.websocket_message_failed': 'Dashboard websocket message could not be parsed or dispatched',
  'ui.websocket_connect_failed': 'Dashboard websocket connection attempt failed before retry',
  'ui.output_contract_mismatch': 'Dashboard API response did not match its command output schema in development',
  'ui.optional_api_read_failed': 'Dashboard optional API read failed and the UI degraded that section',
  'ui.table_unpaginated_large_render': 'Design-system table rendered a large unpaginated row set in development',
  'ui.button_icon_accessible_name_missing': 'Design-system icon-only button mounted without an accessible name in development',
} as const

export type OperationalLogName = keyof typeof OPERATIONAL_LOG_CATALOG
